CARS = {
    "TORO": {
        "MODELO": "TORO",
        "SEGURANCA": 8.3,
        "CONSUMO": 6.6,
        "DESEMPENHO": 7.5,
        "MANUTENCAO": 8.7,
        "CONFORTO": 8.3,
        "DESIGN": 9.5,
        "ACESSORIOS": 8.0,
    },
    "DUCATO": {
        "MODELO": "DUCATO",
        "SEGURANCA": 8.3,
        "CONSUMO": 9.0,
        "DESEMPENHO": 7.5,
        "MANUTENCAO": 8.3,
        "CONFORTO": 7,
        "DESIGN": 8.0,
        "ACESSORIOS": 7.0,
    },
    "FIORINO": {
        "MODELO": "FIORINO",
        "SEGURANCA": 8.0,
        "CONSUMO": 9.0,
        "DESEMPENHO": 8.0,
        "MANUTENCAO": 9.0,
        "CONFORTO": 7.0,
        "DESIGN": 7.0,
        "ACESSORIOS": 7.0,
    },
    "CRONOS": {
        "MODELO": "CRONOS",
        "SEGURANCA": 8.3,
        "CONSUMO": 8.2,
        "DESEMPENHO": 8.3,
        "MANUTENCAO": 7.8,
        "CONFORTO": 9.5,
        "DESIGN": 9.5,
        "ACESSORIOS": 7.9,
    },
    "FIAT500": {
        "MODELO": "FIAT 500",
        "SEGURANCA": 8.5,
        "CONSUMO": 8.4,
        "DESEMPENHO": 8.8,
        "MANUTENCAO": 7.5,
        "CONFORTO": 8.3,
        "DESIGN": 9.5,
        "ACESSORIOS": 8.0,
    },
    "MAREA": {
        "MODELO": "MAREA",
        "SEGURANCA": 8.7,
        "CONSUMO": 7.7,
        "DESEMPENHO": 9.5,
        "MANUTENCAO": 7.3,
        "CONFORTO": 9.0,
        "DESIGN": 9.3,
        "ACESSORIOS": 8.4,
    },
    "LINEA": {
        "MODELO": "LINEA",
        "SEGURANCA": 9.1,
        "CONSUMO": 7.9,
        "DESEMPENHO": 8.3,
        "MANUTENCAO": 8.7,
        "CONFORTO": 8.9,
        "DESIGN": 9.3,
        "ACESSORIOS": 8.7,
    },
    "ARGO": {
        "MODELO": "ARGO",
        "SEGURANCA": 8.0,
        "CONSUMO": 8.1,
        "DESEMPENHO": 7.7,
        "MANUTENCAO": 5.7,
        "CONFORTO": 8.6,
        "DESIGN": 9.1,
        "ACESSORIOS": 8.5,
    },
    "RENEGADE": {
        "MODELO": "RENEGADE",
        "SEGURANCA": 9.0,
        "CONSUMO": 6.8,
        "DESEMPENHO": 7.3,
        "MANUTENCAO": 5.7,
        "CONFORTO": 8.7,
        "DESIGN": 9.2,
        "ACESSORIOS": 8.9,
    },
}
